name: 'Action Metadata Semver'
description: 'This action takes in input a valid semver and outputs a list of tags that match the semver.'
author: 'Sandros94'
inputs:
  version:
    required: true
    description: 'A valid semver version.'
  enableLatest:
    required: false
    description: 'Disable the latest tag from the output.'
    default: 'true'
outputs:
  tags:
    description: 'A list of tags that match the semver in the input.'
  isPreRelease:
    description: 'A boolean that indicates if the version is a pre-release.'
runs:
  using: 'node16'
  main: 'dist/index.js'
